[package]
name = "limitador"
version = "0.1.0"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
edition = "2018"

[dependencies]
ttl_cache = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
redis = "0.16"
thiserror = "1.0"

[dev-dependencies]
serial_test = "*"
