[package]
name = "limitador-server"
version = "0.3.0"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limitador = { path = "../limitador" }
tokio = { version = "^1", features = ["full"] }
tonic = "^0.4"
prost = "^0.7"
prost-types = "^0.7"
serde_yaml = "^0.8"
log = "^0.4"
env_logger = "^0.8"
actix-web = "^3"
actix-rt = "^1"
paperclip = { version = "^0.5", features = ["actix"] }
serde = { version = "^1", features = ["derive"] }

[build-dependencies]
tonic-build = "^0.4"
