[package]
name = "limitador"
version = "0.1.2"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
description = "Rate limiter."
homepage = "https://github.com/3scale/limitador"
repository = "https://github.com/3scale/limitador"
documentation = "https://docs.rs/limitador"
edition = "2018"

# We make redis optional to be able to compile for wasm32.
[features]
default = ["redis_storage"]
redis_storage = ["redis"]

[dependencies]
ttl_cache = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1.38"
cfg-if = "0.1"

# Optional dependencies
redis = { version = "0.17", optional = true, features = ["connection-manager"] }

[dev-dependencies]
serial_test = "0.4"
criterion = "0.3"
paste = "0.1"
rand = "0.7"
tokio = { version = "0.2", features = ["rt-core", "macros"] } # To be able to use #[tokio::test]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
