[package]
name = "limitador"
version = "0.1.3"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
description = "Rate limiter."
homepage = "https://github.com/3scale/limitador"
repository = "https://github.com/3scale/limitador"
documentation = "https://docs.rs/limitador"
edition = "2018"

# We make redis optional to be able to compile for wasm32.
[features]
default = ["redis_storage"]
redis_storage = ["redis", "r2d2", "tokio"]

[dependencies]
ttl_cache = "^0.5"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "^1"
futures = "^0.3"
async-trait = "^0.1"
cfg-if = "^1"
prometheus = "^0.11"
lazy_static = "^1.4"

# Optional dependencies
redis = { version = "^0.19", optional = true, features = ["connection-manager", "tokio-comp"] }
r2d2 = { version = "^0.8", optional = true }
tokio = { version = "^1", optional = true, features = ["rt", "macros", "time"] }

[dev-dependencies]
serial_test = "^0.5"
criterion = "^0.3"
paste = "^1"
rand = "^0.8"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
